#! /usr/bin/env php
<?php

require_once __DIR__ . '/../Config.php';
require_once __DIR__ . '/../lib/Core.php';
require_once __DIR__ . '/../common/db/task_rating.php';

db_connect();

$query = 'select id from ia_task';

$results = db_fetch_all($query);
foreach ($results as $row) {
  task_rating_update($row['id']);
}
