#! /usr/bin/env php
<?php

require_once __DIR__ . '/../Config.php';
require_once __DIR__ . '/../lib/Core.php';

$tasks = Model::factory('Task')->find_many();

foreach ($tasks as $task) {
  $tr = TaskRatings::getForTask($task->id);
  if ($tr) {
    $task->rating = $tr->getStarRating();
  } else {
    $task->rating = 0.0;
  }
  $task->save();
}
